### ISSUE TITLE
couldn't access sub-module api

### ISSUE THREAD

**Issue by prayagupa** [kumarshantanu/lein-sub#12] opened 2014-09-05 12:28 UTC
I have 2 projects as below at the same level, 

[A-front/project.clj](https://github.com/prayagupd/nepleaks/tree/master/nepleaks-front)
[B-engine/project.clj](https://github.com/prayagupd/nepleaks/tree/master/nepleaks-engine)

`A-front` submodules `B-engine`.

```
  :sub  ["../B-engine"] 
```

Now, `.clj` inside `A-front` tries to use .clj from `B-engine`. But fails with 

``` bash
$ lein ring server 8989
WARNING: get already refers to: #'clojure.core/get in namespace: a.views.leak, being replaced by: #'clj-http.client/get
WARNING: get already refers to: #'clojure.core/get in namespace: a.views.dashboard, being replaced by: #'clj-http.client/get
Exception in thread "main" java.io.FileNotFoundException: Could not locate b_engine/services/esService__init.class or b_engine/services/esService.clj on classpath: 
    at clojure.lang.RT.load(RT.java:443)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$use.doInvoke(core.clj:5507)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at a.views.dashboard$eval3970$loading__4910__auto____3971.invoke(dashboard.clj:6)
    at nepleaks.views.dashboard$eval3970.invoke(dashboard.clj:6)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$use.doInvoke(core.clj:5507)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at nepleaks.handler$eval1694$loading__4910__auto____1695.invoke(handler.clj:6)
    at nepleaks.handler$eval1694.invoke(handler.clj:6)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at user$eval5.invoke(form-init7919921197556062016.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6608)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.Compiler.loadFile(Compiler.java:7020)
    at clojure.main$load_script.invoke(main.clj:294)
    at clojure.main$init_opt.invoke(main.clj:299)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
Subprocess failed
```

Am I missing some flags with `lein` command?? `lein sub deps` is fine.

**Comment by kumarshantanu** [comment] 2014-09-05 12:54
I am unable to reproduce the issue with a similar setup (but without using _lein-ring_). Could you put up a dummy repo that I can clone to reproduce this issue?

**Comment by prayagupa** [comment] 2014-09-05 16:40
Hi @kumarshantanu , 
To reproduce the issue, you can clone https://github.com/prayagupd/nepleaks.git, 

``` bash
git clone https://github.com/prayagupd/nepleaks.git
cd nepleaks-front
lein ring server
```

**Comment by kumarshantanu** [comment] 2014-09-05 19:27
This does not look like _lein-sub_ issue to me. You can verify that by commenting out _lein-sub_ references in `project.clj` and then running `lein ring server`. Correct me if I am missing something.

Submodules are not automatically included in the classpath of the parent project. You have to use [Leiningen checkouts](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies) for that.

**Comment by kumarshantanu** [comment] 2014-09-07 19:57
Closing this issue. @prayagupd Feel free to reopen if you think I missed anything.

**Closed as completed by kumarshantanu** 2014-09-07 19:57 UTC
